# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 15:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0002_analyzedevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedevent',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='analyzedevent',
            name='event_data',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
