# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0003_auto_20160929_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedevent',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='analyzedevent',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analyzedevent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
