# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0004_auto_20161007_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaytype',
            name='human_readable_name',
            field=models.CharField(default='', help_text='e.g., X-plus -> mu-plus + Y^0', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decaytype',
            name='name',
            field=models.CharField(help_text='e.g., X<sup>0</sup> &rarr;  &pi;<sup>+</sup> + &pi;<sup>-</sup>', max_length=200),
        ),
    ]
