# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0005_auto_20161007_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Taylor University', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='decaytype',
            name='name',
            field=models.CharField(help_text='e.g., X<sup>0</sup> &rarr;  &pi;<sup>+</sup> + &pi;<sup>-</sup>, but written with sup and ampersands, etc.', max_length=200),
        ),
    ]
