# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0008_auto_20171211_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name',)},
        ),
    ]
