# Generated by Django 3.0.6 on 2020-06-02 14:10

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0009_auto_20171229_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedevent',
            name='event_data',
            field=jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
