# Generated by Django 3.0.6 on 2020-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0010_auto_20200602_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
