# Generated by Django 3.0.6 on 2020-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decays', '0011_analyzedevent_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedevent',
            options={'ordering': ['-submitted', '-updated']},
        ),
        migrations.AddField(
            model_name='aliasname',
            name='verbose_name',
            field=models.CharField(blank=True, default='', help_text='e.g., X-plus', max_length=40),
        ),
    ]
