staging:
  hosts:
    ubuntu-server:
      ansible_user: tom
      ansible_host: 10.211.55.53
      server_name: ubuntu
  vars:
    node_env: production
    nginx_config: nginx-simple.conf
    cap_base_abs_dir: "/home/particle-tracks"
    cap_app_abs_dir: "{{ cap_base_abs_dir }}/app"

production:
  hosts:
    particle_tracks:
      ansible_user: tnurkkala
      ansible_host: localhost
      ansible_port: 2222
      server_name: "particle-tracks.physics.taylor.edu"
  vars:
    node_env: production
    nginx_config: nginx-production.conf
    pt_base_abs_dir: "/home/particle-tracks"
    pt_app_abs_dir: "{{ pt_base_abs_dir }}/app"
